# Generated by Django 6.0.4 on 2026-05-12 18:38

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='artworks/')),
                ('video_url', embed_video.fields.EmbedVideoField(blank=True, null=True)),
            ],
        ),
    ]
