# Generated by Django 6.0.4 on 2026-05-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_created_at_alter_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
